#!/bin/sh
#######################################################################
#
# l1nk - a link shortener for terminal which uses l1nk.ir
# Copyright (C) 2017  Farhadhp <farhadhp's_email@somewhere.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################

echo "Welcome to l1nk.ir link shortner - Version: 1.0.0 Beta \n"
echo "Author: Farhad Hassan Pour -> http://farhadhp.ir \n"
echo "Speical thanks from Salvador Immortal \n"
echo "Github: https://github.com/farhadhp/l1nk"
cp l1nk /usr/bin

