#!/bin/sh
echo "Welcome to l1nk.ir link shortner - Version: 1.0.0 Beta \n"
echo "Author: Farhad Hassan Pour -> http://farhadhp.ir \n"
echo "Speical thanks from Salvador Immortal \n"
echo "Github: https://github.com/farhadhp/l1nk"
cp l1nk /usr/bin

