#!/usr/bin/python
import requests,json
import urllib2
import base64
import sys

# author: Farhad Hassan Pour -> http://farhadhp.ir

if len(sys.argv) < 2:
	long_link = raw_input("Plz enter your long link: ")
else:
	long_link = sys.argv[1]

#long_link = raw_input("Plz enter your long link: ")
long_link = base64.b64encode(long_link)
url='http://l1nk.ir/api/v1/public/'+long_link

req = urllib2.Request(url)
req.add_header('Accept', 'application/json')
req.add_header("Content-type", "application/x-www-form-urlencoded")

res = urllib2.urlopen(req)
out=json.load(res)
try:
	print("Short link: "+out["full_short_link"])
except:
	print(out['error'])
